---
image: mischief/docker-golang

env:
  - GOROOT=/usr/local/go
  - PATH=$GOROOT/bin:$PATH
  - GOPATH=/tmp/build/src
  - PATH=/tmp/build/bin:$PATH
  - REPO_DIR=$GOPATH/src/github.com/onsi/auction

script: |
  set -x

  ps auxff

  mkdir -p $(dirname $REPO_DIR)
  mv auction $REPO_DIR

  cd $REPO_DIR

  export GOPATH=${PWD}/Godeps/_workspace:$GOPATH
  export PATH=${PWD}/Godeps/_workspace/bin:$PATH

  go install github.com/onsi/ginkgo/ginkgo
  go get github.com/apcera/gnatsd

  ginkgo
